driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-7.10
    run_list: apt::default
  - name: debian-8.4
    run_list: apt::default
  - name: freebsd-9.3
    run_list: freebsd::portsnap
  - name: freebsd-10.2
    run_list: freebsd::portsnap
  - name: fedora-22
    run_list: yum::dnf_yum_compat
  - name: fedora-23
    run_list: yum::dnf_yum_compat
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default
  - name: opensuse-13.2

suites:
- name: default
  run_list:
  - recipe[build-essential]
  - recipe[ark]
  - recipe[ark_spec]
